### ISSUE TITLE
jmh:compile doesnt work with 0.2.3 ?

### ISSUE THREAD

**Issue by ghost** [ktoso/sbt-jmh#57]
We didn't change any code just upgraded to 0.2.3. Did we miss any step ?
```
java:9: package org.openjdk.jmh.annotations does not exist
[error] org.openjdk.jmh.annotations.CompilerControl

java:10: package org.openjdk.jmh.runner does not exist
[error] org.openjdk.jmh.runner.InfraControl

java:11: cannot find symbol
[error]   symbol:   class ThreadParams
[error]   location: package org.openjdk.jmh.infra
[error] org.openjdk.jmh.infra.ThreadParams

java:12: package org.openjdk.jmh.results does not exist
[error] org.openjdk.jmh.results.BenchmarkTaskResult

java:13: package org.openjdk.jmh.results does not exist
[error] org.openjdk.jmh.results.Result

java:15: package org.openjdk.jmh.results does not exist
[error] org.openjdk.jmh.results.AverageTimeResult
```

**Comment by ktoso** [comment]
Hm, the project is tested using latest and we've also upgraded to it in Akka...
Is there any more details you could share? I'll look into it a bit later.

**Comment by roy-collective** [comment]
Thanks ! Few weeks back we upgraded to 0.2.2, that time there were no issues at all. We were using run and compile.
Until we upgraded yesterday (after seeing it in the Akka bench project). immediately noticed run needs to change to jmh:run and compile for jmh:compile. I tried clean ensured the .ivy2 caches with only proper version

**Comment by ktoso** [comment]
Thanks for the hints, I don't see yet what might have gone wrong but will have a look. I'll keep you posted in this ticket.

**Comment by roy-collective** [comment]
One way to get around the issue was to add `enablePlugins(JmhPlugin)` to the root project in the `build.sbt`. Out benchmarks are not in the root project. This is not the case for 0.2.1 though it works fine.

**Comment by ktoso** [comment]
Thanks a lot for the info! I'm a bit overwhelmed with tasks at the moment,
will try to investigate deeper as soon as I can. Thanks again for the
additional info, this helps a lot

**Comment by japgolly** [comment]
I'm having the same issue.

I've got a public repo in which you can reproduce this, if you haven't been able to.

1. Check out: https://github.com/japgolly/nyaya.git It uses sbt-jmh 0.2.2.
2. `sbt benchmark/run`. :star2: Everything works.
3. Change the version in `project/plugins.sbt` to 0.2.4.
4. `sbt benchmark/run` :boom: 
5. `sbt benchmark/jmh:run` :boom: 
6. `sbt benchmark/jmh:compile` :boom:

**Comment by ktoso** [comment]
I suggest you upgrade first - there's really no reason to stay on a old version like that, we're currently at 2.11.

**Comment by ktoso** [comment]
Note that we don't guarantee any more compatibility than JMH does, please refer to JMH documentation and release notes for migrating up
